from enum import Enum


class AdminCommand(Enum):
    RESTART_INTRODUCTION = "RESTART_INTRODUCTION"
    SEND_FIRST_TIME_REMIND = "SEND_FIRST_TIME_REMIND"
    SEND_INTRO_REMIND = "SEND_INTRO_REMIND"
    SEND_VENTED_REMIND = "SEND_VENTED_REMIND"
    SEND_UNVENTED_REMIND = "SEND_UNVENTED_REMIND"
    RESTART_SESSION = "RESTART_SESSION"
    GO_TO_ASK_MOOD = "GO_TO_ASK_MOOD"

    admin_command_list = [
        RESTART_INTRODUCTION,
        SEND_FIRST_TIME_REMIND,
        SEND_INTRO_REMIND,
        SEND_VENTED_REMIND,
        SEND_UNVENTED_REMIND,
        RESTART_SESSION,
        GO_TO_ASK_MOOD
    ]
